export const GET_MOVIES = 'GET_MOVIES';
export const REMOVE_MOVIES = 'REMOVE_MOVIES';
export const GET_FAVORITES = 'GET_FAVORITES';
export const ADD_FAVORITES = 'ADD_FAVORITES';
export const REMOVE_FAVORITES = 'REMOVE_FAVORITES';
export const SET_DEFAULT_MOVIES = 'SET_DEFAULT_MOVIES';
